### ISSUE TITLE
License Info?

### ISSUE THREAD

**Issue by kolodny** [baudehlo/node-phantom-ws#1]
There's no license associated with this project. Can I use this in my project?

**Comment by baudehlo** [comment]
Sure, but I suggest you use node-phantom-simple instead.

Both are MIT licensed.

**Comment by kolodny** [comment]
[I already am,](https://github.com/kolodny/co-phantom/blob/master/lib/index.js#L1) I just liked that idea of not polling the the bridge, Any reason you gave it up and went with simple (http) instead?

**Comment by baudehlo** [comment]
Basically stability. WS wasn't stable enough, and more importantly for
where I was using it, I couldn't make it support node's cluster mode
properly.

I spent a lot of time thinking about the most simple way to make
communication work with both events and the phantom sync function calls,
and plain HTTP just worked best.
